os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "10.15.3"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
    - script:
      - ng --version
    - script:
      - ng build --prod

    ## Deploy Stage ##
    - stage: Deploy App
      if: branch = master
      #script: ng build --prod
      script: ng --version


notifications:
  email:
    on_failure: always
    on_success: never
