os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "10.15.3"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - /.*/

before_install:
  - sudo apt-get update

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    - stage: Build App
      name: "ng build"
      script:
        - ng --version
        - ng build

#    - stage: Test App
#      name: "ng test"
#      script: ng test

    - stage: Deploy App
      script: ng build --prod


notifications:
  email:
    on_failure: always
    on_success: change
