name: Publish to Docker hub

on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jpavanaryan/eshopping-ui:latest
